//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF2_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrderId { get; set; }
        public int SKU { get; set; }
        public int Count { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Order Order { get; set; }
    }
}
